// Code generated by hertz generator.

package main

import (
	"esp32/biz/infra"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	infra.Init()
	h := server.Default()

	register(h)
	h.Spin()
}
