// Code generated by hertz generator.

package main

import (
	handler "esp32/biz/handler"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)
	r.GET("/ws_chat", handler.WSChat)
	r.POST("/asr", handler.ASR)
	r.GET("/tts", handler.TTS)
}
