// Code generated by hertz generator.

package esp32

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sayhelloMw() []app.HandlerFunc {
	// your code...
	return nil
}
