// Code generated by hertz generator.

package esp32

import (
	"context"

	esp32 "esp32/biz/model/esp32"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// SayHello .
// @router /hello [GET]
func SayHello(ctx context.Context, c *app.RequestContext) {
	var err error
	var req esp32.Request
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(esp32.Response)

	c.JSON(consts.StatusOK, resp)
}
