// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	esp32 "esp32/biz/router/esp32"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	esp32.Register(r)
}
